### PR TITLE
CASMPET-6161: Add cert-manager namespace to drydock from cray-certman…

### PR DESCRIPTION
**Pull request by mitchty**
## Summary and Scope

Cray-drydock gains the cert-manager namespace from cray-certmanager-init.

**Notes from Lindsay E**
This change is related to CASMPET-6161. [https://github.com/Cray-HPE/cray-certmanager/commit/571f2ba382597ecf56098e72cdd403db9321786d#diff-124d6dd9db47be9ec91ed[…]820f5bd40237caf0d8c2ddffc1](https://github.com/Cray-HPE/cray-certmanager/commit/571f2ba382597ecf56098e72cdd403db9321786d#diff-124d6dd9db47be9ec91ed0d890d2de9b45c9a8820f5bd40237caf0d8c2ddffc1)
In CASMPET-6161 cray-certmanager-init chart was removed. This is the chart that was creating the cert-manger namespace. Now the namespace is created by cray-drydock.

[CASMPET-7133](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7133) is tracking the merging and releasing of this PR since CASMPET-6161 has already been closed.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Review by bklei — APPROVED** [review]

**Review by kimjensen-hpe — APPROVED** [review]

**Review by kimjensen-hpe — APPROVED** [review]

**Review by kimjensen-hpe — APPROVED** [review]

**Comment by dborman-hpe** [comment]
Huh, this just adds the namespace without adding a LimitRange (default resources).  That got me curios, so on mug I checked:
```
mug-pit:~ # kubectl get pods -n cert-manager -o yaml | grep qosClass
    qosClass: BestEffort
    qosClass: BestEffort
    qosClass: BestEffort
    qosClass: BestEffort
    qosClass: BestEffort
    qosClass: BestEffort
    qosClass: BestEffort
    qosClass: BestEffort
    qosClass: BestEffort
```
None of the pods in the cert-manager namespace set any resource request/limits (if they did, the qosClass would be `Burstable`)  We're not doing it now, so it doesn't need to be part of this PR, but we should probably look into at least getting resource requests set for these pods.

**Review by dborman-hpe — APPROVED** [review]

**Review by dborman-hpe — CHANGES_REQUESTED** [review]
The chart version needs to be updated.

**Comment by leliasen-hpe** [comment]
I have created this ticket for CSM 1.6 to set resource requests in the cert-manager pods: https://jira-pro.it.hpe.com:8443/browse/CASMPET-7132.

**Comment by leliasen-hpe** [comment]
> The chart version needs to be updated.

I have bumped the chart version to 2.18.3.

**Review by dborman-hpe — APPROVED** [review]
LGTM

**Pull request merged**
